### ISSUE TITLE
Ajuste no método insert do Service

### ISSUE THREAD

**Issue by oliveiralex** [VivianeMSiqueira/dsclient-bootcamp#1]
Olá Viviane, tudo bem? Meu nome é Alexandre e eu estou corrigindo sua atividade.

Seu trabalho foi aprovado, parabéns! Mas para ficar 100%, peço que você faça um ajuste no método insert do seu Service. Ao tentar inserir um novo cliente (POST), os campos referentes ao cpf, income, birthdate e children estão sendo inseridos como nulo. Segue o exemplo que eu tentei realizar:

Ao tentar inserir o usuário

```
{
    "name": "Silvio Almeida",
    "cpf": "14443278901",
    "income": 4500.0,
    "birthDate": "1979-07-20T10:30:00Z",
    "children": 1
}
```

No retorno é apresentado o seguinte retorno:

```
{
    "id": 30,
    "name": "Silvio Almeida",
    "cpf": null,
    "income": null,
    "birthDate": null,
    "children": null
} 
```

Dei uma olhada rápida e aparentemente o problema está no método insert do ClientService. Perceba que ao invés de instanciar um novo cliente, você deve obter o cliente a partir do DTO, usando a seguinte chamada:

`Client entity = dto.toEntity();`

Peço que você faça os seguintes ajustes!
Abraço

**Comment by VivianeMSiqueira** [comment]
Consertado. Obrigada!
